[mypy]
python_version = 3.12
files = tools
exclude = ^tools[/\\]tests[/\\]
disallow_untyped_defs = True
check_untyped_defs = True
allow_untyped_globals = True
allow_redefinition = True
warn_unused_ignores = True
show_error_codes = True
