"""Publish src/ as one Advanced Formula Environment module.

Importing one src/ module into the Advanced Formula Environment recreates its
functions under the container's own name (Dates.CountDOWλ), and one library
cannot be six containers. This tool joins the six module texts, in the order
compile_sources.py compiles them, into one text that imports as the module oz
and so recreates every shipped oz. name. Each module's text is the published
source verbatim, the same bytes verify_afe.py holds the AFE store to, so the
join is bound to the workbook commit it ships with. --check reports whether
the tracked output is current without writing.

The checks prove that every statement in the join is a declaration, that the
join declares each shipped name exactly once and nothing else, keeps
case-insensitively distinct names, and is LF-only with a final newline. They do not exercise the import route; RELEASING.md and
docs/workbook-use.md say what native evidence that needs.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from compile_sources import MODULES, NAMESPACE  # noqa: E402
from verify_afe import workbook_names  # noqa: E402
from verify_sources import NAME, statements  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

BANNER = (
    "/*  Ozzit: every module of src/ joined as one Advanced Formula Environment module.\n"
    "    Generated by tools/build_module.py; edit src/ and rebuild, never this file.\n"
    "    Import it as a new module named oz to recreate the shipped oz. names. */\n\n"
)
DOUBLE_PREFIX = re.compile(re.escape(NAMESPACE) + r"\." + re.escape(NAMESPACE) + r"\.")


def build(src: Path) -> str:
    """The six module texts, verbatim, each under its own banner."""
    parts = [BANNER]
    for module in MODULES:
        text = (src / f"{module}.txt").read_text(encoding="utf-8")
        if not text.endswith("\n"):
            text += "\n"
        parts.append(f"/*  ===== {module} ===== */\n{text}\n")
    return "".join(parts)


def declared_names(text: str) -> list[str]:
    """Every name a module text declares, in order, including the help tables."""
    names = []
    for statement in statements(text):
        match = NAME.match(statement)
        if match:
            names.append(match.group(1))
    return names


def check(text: str, workbook: Path, index: Path) -> list[str]:
    """Why the joined text could not stand in for the workbook's names."""
    failures: list[str] = []
    if "\r" in text:
        failures.append("module text contains a carriage return")
    if not text.endswith("\n"):
        failures.append("module text does not end with a newline")
    if DOUBLE_PREFIX.search(text):
        failures.append(f"module text contains a doubled {NAMESPACE}. prefix")
    declared = declared_names(text)
    # A statement that is not a declaration would be copied into the published
    # module and fail on import; verify_sources.py rejects it too, but this
    # tool must not report success on its own for text it cannot vouch for.
    for statement in statements(text):
        if statement.strip() and not NAME.match(statement):
            failures.append(f"statement is not a declaration: {statement.strip()[:60]!r}")
    folded: dict[str, str] = {}
    for name in declared:
        earlier = folded.setdefault(name.casefold(), name)
        if earlier != name or declared.count(name) > 1:
            failures.append(f"{name} is declared more than once (case-insensitively)")
    shipped = {name[len(NAMESPACE) + 1 :] for name in workbook_names(workbook)}
    with index.open(encoding="utf-8-sig", newline="") as handle:
        indexed = {row["function"][len(NAMESPACE) + 1 :] for row in csv.DictReader(handle)}
    for label, expected in (("workbook", shipped), ("functions.csv", indexed)):
        for name in sorted(expected - set(declared)):
            failures.append(f"{label} ships {NAMESPACE}.{name}, which the module text does not declare")
        for name in sorted(set(declared) - expected):
            failures.append(f"module text declares {name}, which the {label} does not ship")
    return sorted(set(failures))


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Publish src/ as one Advanced Formula Environment module.",
        allow_abbrev=False,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("src", nargs="?", type=Path, default=Path("src"), help="source directory")
    parser.add_argument("output", nargs="?", type=Path, default=Path("oz.txt"), help="output module")
    parser.add_argument("workbook", nargs="?", type=Path, default=Path("ozzit.xlsx"),
                        help="authoritative workbook")
    parser.add_argument("index", nargs="?", type=Path, default=Path("functions.csv"),
                        help="function index")
    parser.add_argument("--check", action="store_true", help="check the output without writing")
    args = parser.parse_intermixed_args(argv)
    output = args.output
    text = build(args.src)
    failures = check(text, args.workbook, args.index)
    for failure in failures:
        print(f"FAIL: {failure}")
    if failures:
        return 1
    if args.check:
        current = output.read_bytes() if output.is_file() else b""
        if current != text.encode("utf-8"):
            print(f"FAIL: {output} is stale; run python tools/build_module.py")
            return 1
        print(f"OK: {output} is current, {len(declared_names(text))} names")
        return 0
    output.write_bytes(text.encode("utf-8"))
    print(f"wrote {output}: {len(declared_names(text))} names, {len(text.encode('utf-8'))} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
