"""Create and independently verify Ozzit's copy-only workbook release bundle.

The current workbook cannot be regenerated byte-for-byte from the disclosed
upstream input. This tool therefore copies the exact tracked workbook, proves it
matches the reviewed base manifest, and writes deterministic verification evidence.
It does not tag, upload or publish anything.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, TypedDict


ASSETS = ("ozzit.xlsx", "provenance.json", "SHA256SUMS")
CHECKSUMMED_ASSETS = ("ozzit.xlsx", "provenance.json")
GATE_COMMANDS = (
    "python tools/verify_workbook.py ozzit.xlsx",
    "python tools/verify_sources.py ozzit.xlsx src",
    "python tools/verify_signatures.py src",
    "python tools/verify_previous_names.py functions.csv",
    "python tools/verify_index.py ozzit.xlsx src functions.csv",
    "python tools/verify_afe.py ozzit.xlsx src",
)
LIMITATIONS = (
    "The bundle copies the reviewed tracked workbook; it does not regenerate it from upstream.",
    "The documented Mypy, unit, native Excel and cache gates remain required before publication.",
)
BASE_KEYS = {
    "git_blob_sha1",
    "last_workbook_commit",
    "path",
    "schema",
    "sha256",
    "size",
}
VERSION_RE = re.compile(r"(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)")
COMMIT_RE = re.compile(r"[0-9a-f]{40}")
SHA256_RE = re.compile(r"[0-9a-f]{64}")
SHA1_RE = re.compile(r"[0-9a-f]{40}")


class GateResult(TypedDict):
    command: str
    output: str


def sha256_file(path: Path) -> str:
    """Return the lowercase SHA-256 of one regular file."""
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git_blob_sha1(path: Path) -> str:
    """Return the Git blob object ID for a file without invoking Git."""
    data = path.read_bytes()
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data, usedforsecurity=False).hexdigest()


def validate_version(value: str) -> str:
    """Accept only a canonical three-part numeric release version."""
    if VERSION_RE.fullmatch(value) is None:
        raise ValueError("version must be canonical X.Y.Z without a v prefix")
    return value


def validate_source_commit(value: str) -> str:
    """Accept only a full lowercase Git commit object ID."""
    if COMMIT_RE.fullmatch(value) is None:
        raise ValueError("source commit must be a full 40-character lowercase SHA")
    return value


def _unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    """Build a JSON object while rejecting duplicate member names."""
    document: dict[str, Any] = {}
    for key, value in pairs:
        if key in document:
            raise ValueError(f"duplicate JSON member: {key}")
        document[key] = value
    return document


def _load_json_object(path: Path) -> dict[str, Any]:
    """Read a UTF-8 JSON document whose root must be an object."""
    try:
        loaded: Any = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_unique_object,
        )
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid JSON in {path.name}: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ValueError(f"{path.name} must contain a JSON object")
    return loaded


def canonical_json(document: object) -> bytes:
    """Serialise a JSON-compatible value with deterministic UTF-8 bytes."""
    return (
        json.dumps(
            document,
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        )
        + "\n"
    ).encode("utf-8")


def verify_base_workbook(workbook: Path, manifest: Path) -> dict[str, Any]:
    """Prove a workbook is the exact byte sequence locked by the base manifest."""
    if not workbook.is_file() or workbook.is_symlink():
        raise ValueError("base workbook must be a regular non-symlink file")
    if not manifest.is_file() or manifest.is_symlink():
        raise ValueError("base workbook manifest must be a regular non-symlink file")
    document = _load_json_object(manifest)
    if set(document) != BASE_KEYS:
        raise ValueError("base workbook manifest has an unexpected schema")
    if type(document["schema"]) is not int or document["schema"] != 1:
        raise ValueError("base workbook manifest schema must be 1")
    if document["path"] != "ozzit.xlsx":
        raise ValueError("base workbook manifest path must be ozzit.xlsx")
    if type(document["size"]) is not int or document["size"] < 1:
        raise ValueError("base workbook manifest size must be a positive integer")
    if not isinstance(document["sha256"], str) or SHA256_RE.fullmatch(document["sha256"]) is None:
        raise ValueError("base workbook manifest SHA-256 is invalid")
    if not isinstance(document["git_blob_sha1"], str) or SHA1_RE.fullmatch(document["git_blob_sha1"]) is None:
        raise ValueError("base workbook manifest Git blob SHA-1 is invalid")
    if not isinstance(document["last_workbook_commit"], str):
        raise ValueError("base workbook manifest last commit is invalid")
    validate_source_commit(document["last_workbook_commit"])

    actual = {
        "git_blob_sha1": git_blob_sha1(workbook),
        "sha256": sha256_file(workbook),
        "size": workbook.stat().st_size,
    }
    expected = {key: document[key] for key in actual}
    if actual != expected:
        raise ValueError("base workbook bytes do not match release/workbook-base.json")
    return document


def _git_output(root: Path, *arguments: str) -> str:
    """Run one closed read-only Git query and return its trimmed UTF-8 output."""
    completed = subprocess.run(
        ["git", *arguments],
        cwd=root,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
        timeout=30,
    )
    return completed.stdout.strip()


def verify_repository_base(root: Path, base: dict[str, Any]) -> None:
    """Bind the base manifest's Git claims to the candidate checkout."""
    tracked = _git_output(root, "ls-files", "--error-unmatch", "--", "ozzit.xlsx")
    if tracked != "ozzit.xlsx":
        raise ValueError("base workbook must be tracked as ozzit.xlsx")
    blob = _git_output(root, "hash-object", "--", "ozzit.xlsx")
    if blob != base["git_blob_sha1"]:
        raise ValueError("base workbook Git blob does not match the manifest")
    last_commit = _git_output(
        root,
        "log",
        "-1",
        "--format=%H",
        "--",
        "ozzit.xlsx",
    )
    if last_commit != base["last_workbook_commit"]:
        raise ValueError("base workbook last-change commit does not match Git history")


def _normalise_gate_output(text: str, root: Path, workbook: Path) -> str:
    """Remove checkout-specific paths and line-ending differences from gate output."""
    replacements = {
        str(workbook.resolve()): "ozzit.xlsx",
        str((root / "functions.csv").resolve()): "functions.csv",
        str((root / "src").resolve()): "src",
        str(root.resolve()): ".",
    }
    normalised = text
    for source in sorted(replacements, key=len, reverse=True):
        normalised = normalised.replace(source, replacements[source])
        normalised = normalised.replace(source.replace("\\", "/"), replacements[source])
    return normalised.replace("\\", "/").replace("\r\n", "\n").rstrip("\n")


def run_semantic_gates(root: Path, workbook: Path) -> list[GateResult]:
    """Run the six deterministic gates bound to the staged workbook and source views."""
    specifications: tuple[tuple[str, tuple[Path, ...], str], ...] = (
        (
            "verify_workbook.py",
            (workbook,),
            GATE_COMMANDS[0],
        ),
        (
            "verify_sources.py",
            (workbook, root / "src"),
            GATE_COMMANDS[1],
        ),
        (
            "verify_signatures.py",
            (root / "src",),
            GATE_COMMANDS[2],
        ),
        (
            "verify_previous_names.py",
            (root / "functions.csv",),
            GATE_COMMANDS[3],
        ),
        (
            "verify_index.py",
            (workbook, root / "src", root / "functions.csv"),
            GATE_COMMANDS[4],
        ),
        (
            "verify_afe.py",
            (workbook, root / "src"),
            GATE_COMMANDS[5],
        ),
    )
    results: list[GateResult] = []
    for script, arguments, display in specifications:
        completed = subprocess.run(
            [
                sys.executable,
                "-X",
                "utf8",
                str(root / "tools" / script),
                *(str(argument) for argument in arguments),
            ],
            cwd=root,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            check=False,
            timeout=120,
        )
        output = _normalise_gate_output(completed.stdout, root, workbook)
        if completed.returncode != 0:
            detail = f"\n{output}" if output else ""
            raise RuntimeError(f"{display} failed with exit code {completed.returncode}{detail}")
        results.append({"command": display, "output": output})
    return results


def _provenance(
    base: dict[str, Any],
    version: str,
    source_commit: str,
    gate_results: list[GateResult],
) -> dict[str, Any]:
    """Build the deterministic provenance document for a staged workbook."""
    return {
        "assets": list(ASSETS),
        "project": "Ozzit",
        "schema": 1,
        "source": {
            "commit": source_commit,
            "workbook_path": "ozzit.xlsx",
        },
        "verification": {
            "limitations": list(LIMITATIONS),
            "native_gates": {
                "included": False,
                "required_before_publication": True,
            },
            "static_gates": gate_results,
        },
        "version": version,
        "workbook": {
            "base_manifest": "release/workbook-base.json",
            "copy_only": True,
            "git_blob_sha1": base["git_blob_sha1"],
            "last_workbook_commit": base["last_workbook_commit"],
            "sha256": base["sha256"],
            "size": base["size"],
        },
    }


def _checksum_bytes(checksums: dict[str, str]) -> bytes:
    """Serialise the closed checksum inventory in stable filename order."""
    return "".join(
        f"{checksums[name]}  {name}\n" for name in sorted(checksums)
    ).encode("ascii")


def parse_checksums(path: Path) -> dict[str, str]:
    """Parse a canonical SHA256SUMS file and reject ambiguous entries."""
    try:
        data = path.read_bytes()
        text = data.decode("ascii")
    except (OSError, UnicodeDecodeError) as exc:
        raise ValueError(f"invalid SHA256SUMS: {exc}") from exc
    if not text.endswith("\n") or "\r" in text:
        raise ValueError("SHA256SUMS must use canonical LF-terminated lines")
    checksums: dict[str, str] = {}
    for line in text.splitlines():
        match = re.fullmatch(r"([0-9a-f]{64})  ([A-Za-z0-9._-]+)", line)
        if match is None:
            raise ValueError("SHA256SUMS contains a malformed line")
        digest, name = match.groups()
        if name in checksums:
            raise ValueError(f"SHA256SUMS repeats {name}")
        checksums[name] = digest
    if tuple(sorted(checksums)) != tuple(sorted(CHECKSUMMED_ASSETS)):
        raise ValueError("SHA256SUMS has an unexpected inventory")
    if data != _checksum_bytes(checksums):
        raise ValueError("SHA256SUMS is not canonically ordered")
    return checksums


def verify_bundle(
    bundle: Path,
    *,
    root: Path,
    check_semantics: bool = True,
) -> dict[str, Any]:
    """Verify exact inventory, hashes, provenance and optionally all workbook gates."""
    if not bundle.is_dir() or bundle.is_symlink():
        raise ValueError("bundle must be a regular non-symlink directory")
    entries = list(bundle.iterdir())
    if any(not entry.is_file() or entry.is_symlink() for entry in entries):
        raise ValueError("bundle inventory may contain only regular non-symlink files")
    if sorted(entry.name for entry in entries) != sorted(ASSETS):
        raise ValueError("bundle inventory does not match the three reviewed assets")

    checksums = parse_checksums(bundle / "SHA256SUMS")
    for name, expected in checksums.items():
        if sha256_file(bundle / name) != expected:
            raise ValueError(f"checksum mismatch for {name}")

    provenance_path = bundle / "provenance.json"
    provenance = _load_json_object(provenance_path)
    if provenance_path.read_bytes() != canonical_json(provenance):
        raise ValueError("provenance.json is not canonical JSON")
    if set(provenance) != {
        "assets",
        "project",
        "schema",
        "source",
        "verification",
        "version",
        "workbook",
    }:
        raise ValueError("provenance.json has an unexpected top-level schema")
    if (
        type(provenance.get("schema")) is not int
        or provenance.get("schema") != 1
        or provenance.get("project") != "Ozzit"
    ):
        raise ValueError("provenance.json identifies an unsupported bundle")
    if provenance.get("assets") != list(ASSETS):
        raise ValueError("provenance asset inventory is invalid")

    version = provenance.get("version")
    if not isinstance(version, str):
        raise ValueError("provenance version is invalid")
    validate_version(version)
    source = provenance.get("source")
    if not isinstance(source, dict) or set(source) != {"commit", "workbook_path"}:
        raise ValueError("provenance source is invalid")
    commit = source.get("commit")
    if not isinstance(commit, str):
        raise ValueError("provenance source commit is invalid")
    validate_source_commit(commit)
    if source.get("workbook_path") != "ozzit.xlsx":
        raise ValueError("provenance workbook path is invalid")

    base = verify_base_workbook(
        bundle / "ozzit.xlsx",
        root / "release" / "workbook-base.json",
    )
    expected_workbook = {
        "base_manifest": "release/workbook-base.json",
        "copy_only": True,
        "git_blob_sha1": base["git_blob_sha1"],
        "last_workbook_commit": base["last_workbook_commit"],
        "sha256": base["sha256"],
        "size": base["size"],
    }
    if provenance.get("workbook") != expected_workbook:
        raise ValueError("provenance workbook evidence does not match the base workbook")
    workbook_evidence = provenance.get("workbook")
    if not isinstance(workbook_evidence, dict) or type(workbook_evidence.get("copy_only")) is not bool:
        raise ValueError("provenance workbook copy-only claim is invalid")

    verification = provenance.get("verification")
    if not isinstance(verification, dict):
        raise ValueError("provenance verification evidence is invalid")
    gates = verification.get("static_gates")
    if not isinstance(gates, list) or any(
        not isinstance(result, dict)
        or set(result) != {"command", "output"}
        or not isinstance(result["command"], str)
        or not isinstance(result["output"], str)
        for result in gates
    ):
        raise ValueError("provenance static gate evidence is invalid")
    if [result["command"] for result in gates] != list(GATE_COMMANDS):
        raise ValueError("provenance static gate sequence is invalid")
    expected_verification_fields = {
        "limitations": list(LIMITATIONS),
        "native_gates": {
            "included": False,
            "required_before_publication": True,
        },
    }
    if set(verification) != {"limitations", "native_gates", "static_gates"} or any(
        verification.get(key) != value
        for key, value in expected_verification_fields.items()
    ):
        raise ValueError("provenance verification claims are invalid")
    native_gates = verification.get("native_gates")
    if not isinstance(native_gates, dict) or any(
        type(native_gates.get(key)) is not bool
        for key in ("included", "required_before_publication")
    ):
        raise ValueError("provenance native gate claims must be Boolean")
    if check_semantics:
        actual_gates = run_semantic_gates(root, bundle / "ozzit.xlsx")
        if actual_gates != gates:
            raise ValueError("semantic gate evidence does not match an independent run")
    return provenance


def create_bundle(
    *,
    root: Path,
    workbook: Path,
    base_manifest: Path,
    output: Path,
    version: str,
    source_commit: str,
) -> dict[str, Any]:
    """Stage, verify and atomically name one deterministic no-overwrite bundle."""
    validate_version(version)
    validate_source_commit(source_commit)
    root = root.resolve()
    workbook = workbook.resolve()
    base_manifest = base_manifest.resolve()
    output = output.absolute()
    if output.resolve(strict=False).is_relative_to(root):
        raise ValueError("release bundle output must be outside the source repository")
    if os.path.lexists(output):
        raise FileExistsError(f"release bundle destination already exists: {output}")
    parent = output.parent
    if not parent.is_dir() or parent.is_symlink():
        raise ValueError("release bundle parent must be an existing non-symlink directory")

    base = verify_base_workbook(workbook, base_manifest)
    staging = Path(tempfile.mkdtemp(prefix=f".{output.name}-", dir=parent))
    try:
        staged_workbook = staging / "ozzit.xlsx"
        shutil.copyfile(workbook, staged_workbook)
        verify_base_workbook(staged_workbook, base_manifest)
        gates = run_semantic_gates(root, staged_workbook)
        provenance = _provenance(base, version, source_commit, gates)
        (staging / "provenance.json").write_bytes(canonical_json(provenance))
        checksums = {
            name: sha256_file(staging / name) for name in CHECKSUMMED_ASSETS
        }
        (staging / "SHA256SUMS").write_bytes(_checksum_bytes(checksums))
        verify_bundle(staging, root=root, check_semantics=False)
        if os.path.lexists(output):
            raise FileExistsError(f"release bundle destination already exists: {output}")
        staging.rename(output)
        return provenance
    finally:
        if staging.exists():
            shutil.rmtree(staging)


def current_commit(root: Path) -> str:
    """Return the exact commit checked out at root."""
    return validate_source_commit(_git_output(root, "rev-parse", "--verify", "HEAD"))


def ensure_clean_checkout(root: Path) -> None:
    """Refuse provenance for a commit while tracked or untracked changes exist."""
    if _git_output(root, "status", "--porcelain", "--untracked-files=all"):
        raise ValueError("candidate checkout must be clean before staging a release bundle")


def build_parser() -> argparse.ArgumentParser:
    """Build the closed command-line interface."""
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    create = commands.add_parser("create", help="create a new deterministic bundle")
    create.add_argument("--version", required=True)
    create.add_argument("--source-commit")
    create.add_argument("--output", required=True, type=Path)
    verify = commands.add_parser("verify", help="independently verify an existing bundle")
    verify.add_argument("--bundle", required=True, type=Path)
    verify.add_argument("--version")
    verify.add_argument("--source-commit")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Create or verify a bundle from the repository containing this script."""
    arguments = build_parser().parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    if arguments.command == "create":
        ensure_clean_checkout(root)
        head = current_commit(root)
        base = verify_base_workbook(
            root / "ozzit.xlsx",
            root / "release" / "workbook-base.json",
        )
        verify_repository_base(root, base)
        requested = arguments.source_commit
        source_commit = head if requested is None else validate_source_commit(requested)
        if source_commit != head:
            raise ValueError("source commit must equal the candidate checkout HEAD")
        provenance = create_bundle(
            root=root,
            workbook=root / "ozzit.xlsx",
            base_manifest=root / "release" / "workbook-base.json",
            output=arguments.output,
            version=arguments.version,
            source_commit=source_commit,
        )
        print(f"OK: created Ozzit {provenance['version']} bundle at {arguments.output}")
        return 0

    ensure_clean_checkout(root)
    head = current_commit(root)
    base = verify_base_workbook(
        root / "ozzit.xlsx",
        root / "release" / "workbook-base.json",
    )
    verify_repository_base(root, base)
    provenance = verify_bundle(arguments.bundle, root=root, check_semantics=True)
    if provenance["source"]["commit"] != head:
        raise ValueError("bundle source commit does not match the candidate checkout HEAD")
    if arguments.version is not None and provenance["version"] != validate_version(arguments.version):
        raise ValueError("bundle version does not match --version")
    if arguments.source_commit is not None:
        expected_commit = validate_source_commit(arguments.source_commit)
        if provenance["source"]["commit"] != expected_commit:
            raise ValueError("bundle source commit does not match --source-commit")
    print(f"OK: verified Ozzit {provenance['version']} bundle at {arguments.bundle}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (
        FileExistsError,
        OSError,
        RuntimeError,
        ValueError,
        subprocess.SubprocessError,
    ) as error:
        raise SystemExit(f"ERROR: {error}") from error
